name: 'Build'

on:
  push:
    branches:
      - build-artifacts

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: |
        curl https://www.sfml-dev.org/files/SFML-2.3.1-windows-vc12-64-bit.zip --output sfml.zip
        expand-archive sfml.zip
        cmake .
        cmake --build . --target ALL_BUILD --config Release
